# -*- mode: sh;-*-
#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
    export BROWSER='open'
    unset SSH_AUTH_SOCK
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
    export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

export GOPATH="$HOME/.local/go"
# Set the list of directories that Zsh searches for programs.
path=(
  #/usr/local/Cellar/chicken/*/bin/
  /usr/local/{sbin,bin}
  /opt/vagrant/bin
  $HOME/.cabal/bin
  $GOPATH/bin
  $(/usr/local/bin/brew --prefix homebrew/php/php56)/bin
  $path
)

export MANPATH="/usr/local/opt/erlang/lib/erlang/man:/usr/local/share/man:$MANPATH"

if [[ -f "$HOME/perl5/perlbrew/etc/bashrc" ]]; then
. $HOME/perl5/perlbrew/etc/bashrc
fi

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
    export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
    export TMPDIR="/tmp/$LOGNAME"
    mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"

# Private stuff
source ~/.zprezto/private
